/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// DeviceConfig : This is the configuration for the device via the various gateways.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceConfig {
    #[serde(rename = "ciot", skip_serializing_if = "Option::is_none")]
    pub ciot: Option<Box<crate::models::CellularIoTConfig>>,
}

impl DeviceConfig {
    /// This is the configuration for the device via the various gateways.
    pub fn new() -> DeviceConfig {
        DeviceConfig { ciot: None }
    }
}
