/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.3 lower-elian
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// DeviceMetadata : This is the metadata for devices.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceMetadata {
    #[serde(rename = "simOperator", skip_serializing_if = "Option::is_none")]
    pub sim_operator: Option<Box<crate::models::NetworkOperator>>,
    #[serde(rename = "ciot", skip_serializing_if = "Option::is_none")]
    pub ciot: Option<Box<crate::models::CellularIoTMetadata>>,
    #[serde(rename = "inet", skip_serializing_if = "Option::is_none")]
    pub inet: Option<Box<crate::models::InetMetadata>>,
}

impl DeviceMetadata {
    /// This is the metadata for devices.
    pub fn new() -> DeviceMetadata {
        DeviceMetadata {
            sim_operator: None,
            ciot: None,
            inet: None,
        }
    }
}
