/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.9.5 spattered-kelvin
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// DeviceStats : This is the statistics for a single device

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceStats {
    #[serde(rename = "bytesUpstream", skip_serializing_if = "Option::is_none")]
    pub bytes_upstream: Option<String>,
    #[serde(rename = "bytesDownstream", skip_serializing_if = "Option::is_none")]
    pub bytes_downstream: Option<String>,
    #[serde(rename = "messagesUpstream", skip_serializing_if = "Option::is_none")]
    pub messages_upstream: Option<String>,
    #[serde(rename = "messagesDownstream", skip_serializing_if = "Option::is_none")]
    pub messages_downstream: Option<String>,
    #[serde(rename = "sessionCount", skip_serializing_if = "Option::is_none")]
    pub session_count: Option<i32>,
}

impl DeviceStats {
    /// This is the statistics for a single device
    pub fn new() -> DeviceStats {
        DeviceStats {
            bytes_upstream: None,
            bytes_downstream: None,
            messages_upstream: None,
            messages_downstream: None,
            session_count: None,
        }
    }
}
