/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.0 lean-joline
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GatewayType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "ciot")]
    Ciot,
    #[serde(rename = "inet")]
    Inet,
    #[serde(rename = "lora")]
    Lora,
    #[serde(rename = "openthread")]
    Openthread,
    #[serde(rename = "zigbee")]
    Zigbee,
    #[serde(rename = "matter")]
    Matter,
    #[serde(rename = "custom")]
    Custom,

}

impl ToString for GatewayType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Ciot => String::from("ciot"),
            Self::Inet => String::from("inet"),
            Self::Lora => String::from("lora"),
            Self::Openthread => String::from("openthread"),
            Self::Zigbee => String::from("zigbee"),
            Self::Matter => String::from("matter"),
            Self::Custom => String::from("custom"),
        }
    }
}

impl Default for GatewayType {
    fn default() -> GatewayType {
        Self::Unknown
    }
}




