/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.0 lean-joline
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GatewayStatus {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "online")]
    Online,
}

impl ToString for GatewayStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Offline => String::from("offline"),
            Self::Online => String::from("online"),
        }
    }
}

impl Default for GatewayStatus {
    fn default() -> GatewayStatus {
        Self::Unknown
    }
}
