/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.5.0 overwrought-dorla
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// GatewayDeviceMetadata : Metadata for devices connected via user-managed gateways. This metadata shows the configuration for the last message transmission

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GatewayDeviceMetadata {
    #[serde(rename = "gatewayId", skip_serializing_if = "Option::is_none")]
    pub gateway_id: Option<String>,
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<::std::collections::HashMap<String, String>>,
}

impl GatewayDeviceMetadata {
    /// Metadata for devices connected via user-managed gateways. This metadata shows the configuration for the last message transmission
    pub fn new() -> GatewayDeviceMetadata {
        GatewayDeviceMetadata {
            gateway_id: None,
            last_update: None,
            params: None,
        }
    }
}
