/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.0 convulsive-launa
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GatewayCioTConfig {
    #[serde(rename = "apn", skip_serializing_if = "Option::is_none")]
    pub apn: Option<String>,
    #[serde(rename = "udpEndpoint", skip_serializing_if = "Option::is_none")]
    pub udp_endpoint: Option<String>,
    #[serde(rename = "coapEndpoint", skip_serializing_if = "Option::is_none")]
    pub coap_endpoint: Option<String>,
}

impl GatewayCioTConfig {
    pub fn new() -> GatewayCioTConfig {
        GatewayCioTConfig {
            apn: None,
            udp_endpoint: None,
            coap_endpoint: None,
        }
    }
}
