/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// Network : Network is the network devices runs on. They communicate via gateway to Span.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Network {
    #[serde(rename = "networkId", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl Network {
    /// Network is the network devices runs on. They communicate via gateway to Span.
    pub fn new() -> Network {
        Network {
            network_id: None,
            tags: None,
        }
    }
}
