/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// SignCertificateResponse : Response when signing a certificate

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SignCertificateResponse {
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
}

impl SignCertificateResponse {
    /// Response when signing a certificate
    pub fn new() -> SignCertificateResponse {
        SignCertificateResponse {
            certificate: None,
            chain: None,
        }
    }
}
