/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.1 humorous-jaron
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateFirmwareBody : This is the request object when updating the firmware image

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateFirmwareBody {
    #[serde(rename = "collectionId", skip_serializing_if = "Option::is_none")]
    pub collection_id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl UpdateFirmwareBody {
    /// This is the request object when updating the firmware image
    pub fn new() -> UpdateFirmwareBody {
        UpdateFirmwareBody {
            collection_id: None,
            version: None,
            tags: None,
            enabled: None,
        }
    }
}
